# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/pb/rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc/pb/rpc.proto',
  package='rpcpb',
  syntax='proto3',
  serialized_pb=_b('\n\x10rpc/pb/rpc.proto\x12\x05rpcpb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x12\n\x10NonParamsRequest\"\"\n\x10GetStateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"3\n\x10\x43reateKeyRequest\x12\r\n\x05\x61lias\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"!\n\x11\x43reateKeyResponse\x12\x0c\n\x04xpub\x18\x01 \x01(\t\"\x1f\n\x0fListKeyResponse\x12\x0c\n\x04xpub\x18\x01 \x03(\t\"2\n\x10\x44\x65leteKeyRequest\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x0c\n\x04xpub\x18\x02 \x01(\t2\xe8\x02\n\nApiService\x12O\n\x08GetState\x12\x17.rpcpb.NonParamsRequest\x1a\x17.rpcpb.GetStateResponse\"\x11\x82\xd3\xe4\x93\x02\x0b\x12\t/v1/state\x12Y\n\tCreateKey\x12\x17.rpcpb.CreateKeyRequest\x1a\x18.rpcpb.CreateKeyResponse\"\x19\x82\xd3\xe4\x93\x02\x13\"\x0e/v1/create-key:\x01*\x12T\n\x07ListKey\x12\x17.rpcpb.NonParamsRequest\x1a\x16.rpcpb.ListKeyResponse\"\x18\x82\xd3\xe4\x93\x02\x12\"\r/v1/list-keys:\x01*\x12X\n\tDeleteKey\x12\x17.rpcpb.DeleteKeyRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14\"\x0f/v1/delete-keys:\x01*b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_NONPARAMSREQUEST = _descriptor.Descriptor(
  name='NonParamsRequest',
  full_name='rpcpb.NonParamsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=104,
)


_GETSTATERESPONSE = _descriptor.Descriptor(
  name='GetStateResponse',
  full_name='rpcpb.GetStateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='rpcpb.GetStateResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=140,
)


_CREATEKEYREQUEST = _descriptor.Descriptor(
  name='CreateKeyRequest',
  full_name='rpcpb.CreateKeyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alias', full_name='rpcpb.CreateKeyRequest.alias', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='rpcpb.CreateKeyRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=193,
)


_CREATEKEYRESPONSE = _descriptor.Descriptor(
  name='CreateKeyResponse',
  full_name='rpcpb.CreateKeyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xpub', full_name='rpcpb.CreateKeyResponse.xpub', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=228,
)


_LISTKEYRESPONSE = _descriptor.Descriptor(
  name='ListKeyResponse',
  full_name='rpcpb.ListKeyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xpub', full_name='rpcpb.ListKeyResponse.xpub', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=261,
)


_DELETEKEYREQUEST = _descriptor.Descriptor(
  name='DeleteKeyRequest',
  full_name='rpcpb.DeleteKeyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='password', full_name='rpcpb.DeleteKeyRequest.password', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xpub', full_name='rpcpb.DeleteKeyRequest.xpub', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=313,
)

DESCRIPTOR.message_types_by_name['NonParamsRequest'] = _NONPARAMSREQUEST
DESCRIPTOR.message_types_by_name['GetStateResponse'] = _GETSTATERESPONSE
DESCRIPTOR.message_types_by_name['CreateKeyRequest'] = _CREATEKEYREQUEST
DESCRIPTOR.message_types_by_name['CreateKeyResponse'] = _CREATEKEYRESPONSE
DESCRIPTOR.message_types_by_name['ListKeyResponse'] = _LISTKEYRESPONSE
DESCRIPTOR.message_types_by_name['DeleteKeyRequest'] = _DELETEKEYREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NonParamsRequest = _reflection.GeneratedProtocolMessageType('NonParamsRequest', (_message.Message,), dict(
  DESCRIPTOR = _NONPARAMSREQUEST,
  __module__ = 'rpc.pb.rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpcpb.NonParamsRequest)
  ))
_sym_db.RegisterMessage(NonParamsRequest)

GetStateResponse = _reflection.GeneratedProtocolMessageType('GetStateResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETSTATERESPONSE,
  __module__ = 'rpc.pb.rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpcpb.GetStateResponse)
  ))
_sym_db.RegisterMessage(GetStateResponse)

CreateKeyRequest = _reflection.GeneratedProtocolMessageType('CreateKeyRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEKEYREQUEST,
  __module__ = 'rpc.pb.rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpcpb.CreateKeyRequest)
  ))
_sym_db.RegisterMessage(CreateKeyRequest)

CreateKeyResponse = _reflection.GeneratedProtocolMessageType('CreateKeyResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATEKEYRESPONSE,
  __module__ = 'rpc.pb.rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpcpb.CreateKeyResponse)
  ))
_sym_db.RegisterMessage(CreateKeyResponse)

ListKeyResponse = _reflection.GeneratedProtocolMessageType('ListKeyResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTKEYRESPONSE,
  __module__ = 'rpc.pb.rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpcpb.ListKeyResponse)
  ))
_sym_db.RegisterMessage(ListKeyResponse)

DeleteKeyRequest = _reflection.GeneratedProtocolMessageType('DeleteKeyRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEKEYREQUEST,
  __module__ = 'rpc.pb.rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpcpb.DeleteKeyRequest)
  ))
_sym_db.RegisterMessage(DeleteKeyRequest)



_APISERVICE = _descriptor.ServiceDescriptor(
  name='ApiService',
  full_name='rpcpb.ApiService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=316,
  serialized_end=676,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetState',
    full_name='rpcpb.ApiService.GetState',
    index=0,
    containing_service=None,
    input_type=_NONPARAMSREQUEST,
    output_type=_GETSTATERESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\013\022\t/v1/state')),
  ),
  _descriptor.MethodDescriptor(
    name='CreateKey',
    full_name='rpcpb.ApiService.CreateKey',
    index=1,
    containing_service=None,
    input_type=_CREATEKEYREQUEST,
    output_type=_CREATEKEYRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\023\"\016/v1/create-key:\001*')),
  ),
  _descriptor.MethodDescriptor(
    name='ListKey',
    full_name='rpcpb.ApiService.ListKey',
    index=2,
    containing_service=None,
    input_type=_NONPARAMSREQUEST,
    output_type=_LISTKEYRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\022\"\r/v1/list-keys:\001*')),
  ),
  _descriptor.MethodDescriptor(
    name='DeleteKey',
    full_name='rpcpb.ApiService.DeleteKey',
    index=3,
    containing_service=None,
    input_type=_DELETEKEYREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\024\"\017/v1/delete-keys:\001*')),
  ),
])
_sym_db.RegisterServiceDescriptor(_APISERVICE)

DESCRIPTOR.services_by_name['ApiService'] = _APISERVICE

# @@protoc_insertion_point(module_scope)
