# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from rpc.pb import rpc_pb2 as rpc_dot_pb_dot_rpc__pb2


class ApiServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetState = channel.unary_unary(
        '/rpcpb.ApiService/GetState',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.NonParamsRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.GetStateResponse.FromString,
        )
    self.CreateKey = channel.unary_unary(
        '/rpcpb.ApiService/CreateKey',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.CreateKeyRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.CreateKeyResponse.FromString,
        )
    self.ListKey = channel.unary_unary(
        '/rpcpb.ApiService/ListKey',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.NonParamsRequest.SerializeToString,
        response_deserializer=rpc_dot_pb_dot_rpc__pb2.ListKeyResponse.FromString,
        )
    self.DeleteKey = channel.unary_unary(
        '/rpcpb.ApiService/DeleteKey',
        request_serializer=rpc_dot_pb_dot_rpc__pb2.DeleteKeyRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class ApiServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetState(self, request, context):
    """state
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateKey(self, request, context):
    """Key
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ApiServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetState': grpc.unary_unary_rpc_method_handler(
          servicer.GetState,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.NonParamsRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.GetStateResponse.SerializeToString,
      ),
      'CreateKey': grpc.unary_unary_rpc_method_handler(
          servicer.CreateKey,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.CreateKeyRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.CreateKeyResponse.SerializeToString,
      ),
      'ListKey': grpc.unary_unary_rpc_method_handler(
          servicer.ListKey,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.NonParamsRequest.FromString,
          response_serializer=rpc_dot_pb_dot_rpc__pb2.ListKeyResponse.SerializeToString,
      ),
      'DeleteKey': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteKey,
          request_deserializer=rpc_dot_pb_dot_rpc__pb2.DeleteKeyRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rpcpb.ApiService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
