// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/pb/rpc.proto

package rpcpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NonParamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonParamsRequest) Reset()         { *m = NonParamsRequest{} }
func (m *NonParamsRequest) String() string { return proto.CompactTextString(m) }
func (*NonParamsRequest) ProtoMessage()    {}
func (*NonParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_26e897ee07835cd8, []int{0}
}
func (m *NonParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonParamsRequest.Unmarshal(m, b)
}
func (m *NonParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonParamsRequest.Marshal(b, m, deterministic)
}
func (dst *NonParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonParamsRequest.Merge(dst, src)
}
func (m *NonParamsRequest) XXX_Size() int {
	return xxx_messageInfo_NonParamsRequest.Size(m)
}
func (m *NonParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NonParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NonParamsRequest proto.InternalMessageInfo

type GetStateResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateResponse) Reset()         { *m = GetStateResponse{} }
func (m *GetStateResponse) String() string { return proto.CompactTextString(m) }
func (*GetStateResponse) ProtoMessage()    {}
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_26e897ee07835cd8, []int{1}
}
func (m *GetStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateResponse.Unmarshal(m, b)
}
func (m *GetStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateResponse.Marshal(b, m, deterministic)
}
func (dst *GetStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateResponse.Merge(dst, src)
}
func (m *GetStateResponse) XXX_Size() int {
	return xxx_messageInfo_GetStateResponse.Size(m)
}
func (m *GetStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateResponse proto.InternalMessageInfo

func (m *GetStateResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type CreateKeyRequest struct {
	Alias                string   `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateKeyRequest) Reset()         { *m = CreateKeyRequest{} }
func (m *CreateKeyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateKeyRequest) ProtoMessage()    {}
func (*CreateKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_26e897ee07835cd8, []int{2}
}
func (m *CreateKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateKeyRequest.Unmarshal(m, b)
}
func (m *CreateKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateKeyRequest.Marshal(b, m, deterministic)
}
func (dst *CreateKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateKeyRequest.Merge(dst, src)
}
func (m *CreateKeyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateKeyRequest.Size(m)
}
func (m *CreateKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateKeyRequest proto.InternalMessageInfo

func (m *CreateKeyRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *CreateKeyRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateKeyResponse struct {
	Xpub                 string   `protobuf:"bytes,1,opt,name=xpub" json:"xpub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateKeyResponse) Reset()         { *m = CreateKeyResponse{} }
func (m *CreateKeyResponse) String() string { return proto.CompactTextString(m) }
func (*CreateKeyResponse) ProtoMessage()    {}
func (*CreateKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_26e897ee07835cd8, []int{3}
}
func (m *CreateKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateKeyResponse.Unmarshal(m, b)
}
func (m *CreateKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateKeyResponse.Marshal(b, m, deterministic)
}
func (dst *CreateKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateKeyResponse.Merge(dst, src)
}
func (m *CreateKeyResponse) XXX_Size() int {
	return xxx_messageInfo_CreateKeyResponse.Size(m)
}
func (m *CreateKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateKeyResponse proto.InternalMessageInfo

func (m *CreateKeyResponse) GetXpub() string {
	if m != nil {
		return m.Xpub
	}
	return ""
}

type ListKeyResponse struct {
	Xpub                 []string `protobuf:"bytes,1,rep,name=xpub" json:"xpub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListKeyResponse) Reset()         { *m = ListKeyResponse{} }
func (m *ListKeyResponse) String() string { return proto.CompactTextString(m) }
func (*ListKeyResponse) ProtoMessage()    {}
func (*ListKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_26e897ee07835cd8, []int{4}
}
func (m *ListKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListKeyResponse.Unmarshal(m, b)
}
func (m *ListKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListKeyResponse.Marshal(b, m, deterministic)
}
func (dst *ListKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListKeyResponse.Merge(dst, src)
}
func (m *ListKeyResponse) XXX_Size() int {
	return xxx_messageInfo_ListKeyResponse.Size(m)
}
func (m *ListKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListKeyResponse proto.InternalMessageInfo

func (m *ListKeyResponse) GetXpub() []string {
	if m != nil {
		return m.Xpub
	}
	return nil
}

type DeleteKeyRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	Xpub                 string   `protobuf:"bytes,2,opt,name=xpub" json:"xpub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteKeyRequest) Reset()         { *m = DeleteKeyRequest{} }
func (m *DeleteKeyRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteKeyRequest) ProtoMessage()    {}
func (*DeleteKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_26e897ee07835cd8, []int{5}
}
func (m *DeleteKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteKeyRequest.Unmarshal(m, b)
}
func (m *DeleteKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteKeyRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteKeyRequest.Merge(dst, src)
}
func (m *DeleteKeyRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteKeyRequest.Size(m)
}
func (m *DeleteKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteKeyRequest proto.InternalMessageInfo

func (m *DeleteKeyRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DeleteKeyRequest) GetXpub() string {
	if m != nil {
		return m.Xpub
	}
	return ""
}

func init() {
	proto.RegisterType((*NonParamsRequest)(nil), "rpcpb.NonParamsRequest")
	proto.RegisterType((*GetStateResponse)(nil), "rpcpb.GetStateResponse")
	proto.RegisterType((*CreateKeyRequest)(nil), "rpcpb.CreateKeyRequest")
	proto.RegisterType((*CreateKeyResponse)(nil), "rpcpb.CreateKeyResponse")
	proto.RegisterType((*ListKeyResponse)(nil), "rpcpb.ListKeyResponse")
	proto.RegisterType((*DeleteKeyRequest)(nil), "rpcpb.DeleteKeyRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiServiceClient is the client API for ApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiServiceClient interface {
	// state
	GetState(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	// Key
	CreateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error)
	ListKey(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*ListKeyResponse, error)
	DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type apiServiceClient struct {
	cc *grpc.ClientConn
}

func NewApiServiceClient(cc *grpc.ClientConn) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) GetState(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.ApiService/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) CreateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error) {
	out := new(CreateKeyResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.ApiService/CreateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) ListKey(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*ListKeyResponse, error) {
	out := new(ListKeyResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.ApiService/ListKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/rpcpb.ApiService/DeleteKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServiceServer is the server API for ApiService service.
type ApiServiceServer interface {
	// state
	GetState(context.Context, *NonParamsRequest) (*GetStateResponse, error)
	// Key
	CreateKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error)
	ListKey(context.Context, *NonParamsRequest) (*ListKeyResponse, error)
	DeleteKey(context.Context, *DeleteKeyRequest) (*empty.Empty, error)
}

func RegisterApiServiceServer(s *grpc.Server, srv ApiServiceServer) {
	s.RegisterService(&_ApiService_serviceDesc, srv)
}

func _ApiService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.ApiService/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetState(ctx, req.(*NonParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_CreateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).CreateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.ApiService/CreateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).CreateKey(ctx, req.(*CreateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_ListKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).ListKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.ApiService/ListKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).ListKey(ctx, req.(*NonParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_DeleteKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).DeleteKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.ApiService/DeleteKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).DeleteKey(ctx, req.(*DeleteKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _ApiService_GetState_Handler,
		},
		{
			MethodName: "CreateKey",
			Handler:    _ApiService_CreateKey_Handler,
		},
		{
			MethodName: "ListKey",
			Handler:    _ApiService_ListKey_Handler,
		},
		{
			MethodName: "DeleteKey",
			Handler:    _ApiService_DeleteKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/pb/rpc.proto",
}

func init() { proto.RegisterFile("rpc/pb/rpc.proto", fileDescriptor_rpc_26e897ee07835cd8) }

var fileDescriptor_rpc_26e897ee07835cd8 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0x95, 0x40, 0x4b, 0xf3, 0x21, 0x68, 0x6a, 0xaa, 0x12, 0x02, 0x07, 0x64, 0x09, 0x81,
	0x2a, 0x91, 0x08, 0xb8, 0x71, 0x03, 0x8a, 0x38, 0x80, 0x00, 0xb5, 0x1c, 0xd8, 0xd1, 0x49, 0xbf,
	0x55, 0xd1, 0xd2, 0xd8, 0xb3, 0x9d, 0x6e, 0xbd, 0xee, 0x15, 0xf6, 0x68, 0x7b, 0x85, 0x1d, 0xf6,
	0x18, 0x53, 0x1c, 0x27, 0x6b, 0xb3, 0xed, 0x96, 0x4f, 0xff, 0xbf, 0x7f, 0x9f, 0xf3, 0x93, 0xc1,
	0x97, 0x22, 0x8d, 0x45, 0x12, 0x4b, 0x91, 0x46, 0x42, 0x72, 0xcd, 0x49, 0x4f, 0x8a, 0x54, 0x24,
	0xe1, 0xab, 0x15, 0xe7, 0xab, 0x1c, 0x63, 0x26, 0xb2, 0x98, 0x15, 0x05, 0xd7, 0x4c, 0x67, 0xbc,
	0x50, 0x75, 0x29, 0x7c, 0x69, 0x53, 0x33, 0x25, 0xe5, 0x61, 0x8c, 0x6b, 0xa1, 0xb7, 0x75, 0x48,
	0x09, 0xf8, 0xbf, 0x79, 0xf1, 0x97, 0x49, 0xb6, 0x56, 0x73, 0x3c, 0x2e, 0x51, 0x69, 0x3a, 0x05,
	0xff, 0x07, 0xea, 0x85, 0x66, 0x1a, 0xe7, 0xa8, 0x04, 0x2f, 0x14, 0x92, 0x09, 0xf4, 0x95, 0x66,
	0xba, 0x54, 0x81, 0xf3, 0xda, 0x79, 0xe7, 0xcd, 0xed, 0x44, 0x67, 0xe0, 0x7f, 0x93, 0xc8, 0x34,
	0xfe, 0xc4, 0xad, 0x3d, 0x4f, 0xc6, 0xd0, 0x63, 0x79, 0xc6, 0x9a, 0x6a, 0x3d, 0x90, 0x10, 0x06,
	0x82, 0x29, 0x75, 0xc2, 0xe5, 0x32, 0x70, 0x4d, 0xd0, 0xce, 0xf4, 0x2d, 0x8c, 0x76, 0x28, 0x76,
	0x25, 0x81, 0x87, 0xa7, 0xa2, 0x4c, 0x2c, 0xc5, 0x7c, 0xd3, 0x37, 0x30, 0xfc, 0x95, 0x29, 0x7d,
	0x77, 0xed, 0x41, 0x5b, 0xfb, 0x0a, 0xfe, 0x0c, 0x73, 0xdc, 0xbb, 0xd5, 0xee, 0x7e, 0x67, 0x7f,
	0x7f, 0xcb, 0x70, 0x6f, 0x56, 0x7d, 0xbc, 0x72, 0x01, 0xbe, 0x88, 0x6c, 0x81, 0x72, 0x93, 0xa5,
	0x48, 0xfe, 0xc0, 0xa0, 0x91, 0x42, 0x9e, 0x47, 0xc6, 0x7b, 0xd4, 0x35, 0x17, 0x36, 0x41, 0x57,
	0x1f, 0x1d, 0x9d, 0x5d, 0x5c, 0x9e, 0xbb, 0x8f, 0x89, 0x17, 0x6f, 0x3e, 0xc4, 0xca, 0x40, 0x0e,
	0xc0, 0x6b, 0xff, 0xb9, 0x25, 0x76, 0x5d, 0x86, 0xc1, 0xed, 0xc0, 0x22, 0x5f, 0x18, 0xe4, 0x33,
	0xfa, 0xb4, 0x42, 0xa6, 0x26, 0x7e, 0x7f, 0x84, 0xdb, 0xcf, 0xce, 0x94, 0xfc, 0x83, 0x47, 0xd6,
	0xd2, 0xfd, 0x57, 0x9d, 0xd8, 0xa0, 0xa3, 0x93, 0x06, 0x06, 0x4b, 0xe8, 0x93, 0x0a, 0x9b, 0x67,
	0x4a, 0x57, 0x50, 0x55, 0x51, 0xff, 0x83, 0xd7, 0x4a, 0x6d, 0xb9, 0x5d, 0xcd, 0xe1, 0x24, 0xaa,
	0x9f, 0x5b, 0xd4, 0x3c, 0xb7, 0xe8, 0x7b, 0xf5, 0xdc, 0x68, 0x68, 0xb8, 0x63, 0x3a, 0xac, 0xb8,
	0x4b, 0x73, 0xaa, 0x21, 0x27, 0x7d, 0xd3, 0xfd, 0x74, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xad, 0x47,
	0xea, 0x50, 0xe1, 0x02, 0x00, 0x00,
}
